// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLKhoHang.Data;

#nullable disable

namespace Quản_lý_kho_hàng.Migrations
{
    [DbContext(typeof(QLKhoHangContext))]
    [Migration("20251116145949_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLKhoHang.Models.BaoCaoNhapHang", b =>
                {
                    b.Property<string>("MaBCN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaHH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongGiaTriNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TongSoLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("MaBCN");

                    b.HasIndex("MaHH");

                    b.ToTable("BaoCaoNhapHang");
                });

            modelBuilder.Entity("QLKhoHang.Models.BaoCaoTonKho", b =>
                {
                    b.Property<string>("MaBCT")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("GiaTriTon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaHH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaBCT");

                    b.HasIndex("MaHH");

                    b.ToTable("BaoCaoTonKho");
                });

            modelBuilder.Entity("QLKhoHang.Models.BaoCaoXuatHang", b =>
                {
                    b.Property<string>("MaBCX")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaHH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongGiaTriXuat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TongSoLuongXuat")
                        .HasColumnType("int");

                    b.HasKey("MaBCX");

                    b.HasIndex("MaHH");

                    b.ToTable("BaoCaoXuatHang");
                });

            modelBuilder.Entity("QLKhoHang.Models.CT_PhieuNhap", b =>
                {
                    b.Property<string>("MaPN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPN", "MaHang");

                    b.HasIndex("MaHang");

                    b.ToTable("CT_PhieuNhap");
                });

            modelBuilder.Entity("QLKhoHang.Models.CT_PhieuXuat", b =>
                {
                    b.Property<string>("MaPX")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DonGiaXuat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPX", "MaHang");

                    b.HasIndex("MaHang");

                    b.ToTable("CT_PhieuXuat");
                });

            modelBuilder.Entity("QLKhoHang.Models.HangHoa", b =>
                {
                    b.Property<string>("MaHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaXuat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaKho")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHang");

                    b.HasIndex("MaKho");

                    b.HasIndex("MaLoai");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("QLKhoHang.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QLKhoHang.Models.Kho", b =>
                {
                    b.Property<string>("MaKho")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChiKho")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKho");

                    b.ToTable("Kho");
                });

            modelBuilder.Entity("QLKhoHang.Models.LoaiHang", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiHang");
                });

            modelBuilder.Entity("QLKhoHang.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QLKhoHang.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNV");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QLKhoHang.Models.PhieuNhap", b =>
                {
                    b.Property<string>("MaPN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPN");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("QLKhoHang.Models.PhieuXuat", b =>
                {
                    b.Property<string>("MaPX")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPX");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("PhieuXuat");
                });

            modelBuilder.Entity("QLKhoHang.Models.BaoCaoNhapHang", b =>
                {
                    b.HasOne("QLKhoHang.Models.HangHoa", "HangHoa")
                        .WithMany("BaoCaoNhapHang")
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("QLKhoHang.Models.BaoCaoTonKho", b =>
                {
                    b.HasOne("QLKhoHang.Models.HangHoa", "HangHoa")
                        .WithMany("BaoCaoTonKho")
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("QLKhoHang.Models.BaoCaoXuatHang", b =>
                {
                    b.HasOne("QLKhoHang.Models.HangHoa", "HangHoa")
                        .WithMany("BaoCaoXuatHang")
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("QLKhoHang.Models.CT_PhieuNhap", b =>
                {
                    b.HasOne("QLKhoHang.Models.HangHoa", "HangHoa")
                        .WithMany("CT_PhieuNhap")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLKhoHang.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("CT_PhieuNhap")
                        .HasForeignKey("MaPN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("QLKhoHang.Models.CT_PhieuXuat", b =>
                {
                    b.HasOne("QLKhoHang.Models.HangHoa", "HangHoa")
                        .WithMany("CT_PhieuXuat")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLKhoHang.Models.PhieuXuat", "PhieuXuat")
                        .WithMany("CT_PhieuXuat")
                        .HasForeignKey("MaPX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("PhieuXuat");
                });

            modelBuilder.Entity("QLKhoHang.Models.HangHoa", b =>
                {
                    b.HasOne("QLKhoHang.Models.Kho", "Kho")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLKhoHang.Models.LoaiHang", "LoaiHang")
                        .WithMany("HangHoa")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("LoaiHang");
                });

            modelBuilder.Entity("QLKhoHang.Models.PhieuNhap", b =>
                {
                    b.HasOne("QLKhoHang.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhap")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLKhoHang.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuNhap")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLKhoHang.Models.PhieuXuat", b =>
                {
                    b.HasOne("QLKhoHang.Models.KhachHang", "KhachHang")
                        .WithMany("PhieuXuat")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLKhoHang.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuXuat")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLKhoHang.Models.HangHoa", b =>
                {
                    b.Navigation("BaoCaoNhapHang");

                    b.Navigation("BaoCaoTonKho");

                    b.Navigation("BaoCaoXuatHang");

                    b.Navigation("CT_PhieuNhap");

                    b.Navigation("CT_PhieuXuat");
                });

            modelBuilder.Entity("QLKhoHang.Models.KhachHang", b =>
                {
                    b.Navigation("PhieuXuat");
                });

            modelBuilder.Entity("QLKhoHang.Models.Kho", b =>
                {
                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("QLKhoHang.Models.LoaiHang", b =>
                {
                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("QLKhoHang.Models.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("QLKhoHang.Models.NhanVien", b =>
                {
                    b.Navigation("PhieuNhap");

                    b.Navigation("PhieuXuat");
                });

            modelBuilder.Entity("QLKhoHang.Models.PhieuNhap", b =>
                {
                    b.Navigation("CT_PhieuNhap");
                });

            modelBuilder.Entity("QLKhoHang.Models.PhieuXuat", b =>
                {
                    b.Navigation("CT_PhieuXuat");
                });
#pragma warning restore 612, 618
        }
    }
}
